### ISSUE TITLE
Default Header Name

### ISSUE THREAD

**Issue by mykeels** [raznerdeveloper/razheaderattribute#1]
Please make the attribute binding use the argument name as the default Header name if the headerName passed to the Attribute is NULL or EMPTY.

E.g. [FromHeader] int page

Should try to obtain the value of the "page" header key.

**Comment by agbanil** [comment]
Sure @mykeels. Thanks for bringing this up

**Comment by agbanil** [comment]
This has been fixed with a recent commit. The Nuget package has been updated as well. I'll be closing this now
